# Generated by Django 5.0.2 on 2024-02-14 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ishturi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ish_id', models.IntegerField(default=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Xato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xato_id', models.IntegerField()),
                ('problem', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Xodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('familiya', models.CharField(max_length=50)),
                ('gender_status', models.CharField(choices=[('erkak', 'erkak'), ('ayol', 'ayol')], max_length=10)),
                ('phone', models.CharField(max_length=13)),
                ('id_raqam', models.IntegerField(default=1, unique=True)),
                ('ish_turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firma.ishturi')),
            ],
        ),
        migrations.CreateModel(
            name='Missed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('izoh', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('xato_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firma.xato')),
                ('xodim_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firma.xodim')),
            ],
        ),
    ]
