# Generated by Django 5.0.2 on 2024-02-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0002_ishturi_xato_xodim_missed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='telefon raqam'),
        ),
    ]
