# Generated by Django 5.0.2 on 2024-02-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xodim',
            name='gender_status',
        ),
        migrations.AddField(
            model_name='xodim',
            name='status',
            field=models.CharField(choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], default='erkak', max_length=10),
        ),
    ]
