# Generated by Django 5.0.2 on 2024-02-15 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0004_remove_xodim_gender_status_xodim_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ishturi',
            new_name='Ishturi_or_Bolim',
        ),
    ]
