# Generated by Django 5.0.2 on 2024-02-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0005_rename_ishturi_ishturi_or_bolim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot_id', models.PositiveIntegerField()),
                ('mahsulot_nomi', models.CharField(max_length=1000)),
            ],
        ),
    ]
