# Generated by Django 5.0.2 on 2024-02-15 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0006_mahsulot'),
    ]

    operations = [
        migrations.AddField(
            model_name='missed',
            name='ish_vaqti',
            field=models.PositiveIntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missed',
            name='mahsulot_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='firma.mahsulot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missed',
            name='xato_soni',
            field=models.PositiveIntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missed',
            name='yaroqli_product_soni',
            field=models.PositiveIntegerField(default=True),
            preserve_default=False,
        ),
    ]
