# Generated by Django 5.0.2 on 2024-02-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0007_missed_ish_vaqti_missed_mahsulot_id_missed_xato_soni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missed',
            name='created',
            field=models.DateTimeField(auto_now=True, db_comment='Date and time when the article was published'),
        ),
    ]
