# Generated by Django 5.0.2 on 2024-02-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0008_alter_missed_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xodim',
            name='ism',
            field=models.CharField(error_messages="This writer's name is too long.", max_length=50),
        ),
    ]
