# Generated by Django 5.0.2 on 2024-02-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0009_alter_xodim_ism'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xodim',
            name='ism',
            field=models.CharField(error_messages={'required': 'this field is required'}, max_length=50),
        ),
    ]
