# Generated by Django 5.0.2 on 2024-02-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0012_alter_missed_xodim_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missed',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_comment='Date and time when the article was published'),
        ),
        migrations.AlterField(
            model_name='missed',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
