# Generated by Django 5.0.2 on 2024-02-18 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0013_alter_missed_created_alter_missed_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('direktor', 'direktor'), ('yordamchi', 'yordamchi'), ("bo'lim_rahbari", "bo'lim_rahbari")], default='yordamchi', max_length=20),
        ),
        migrations.RemoveField(
            model_name='xodim',
            name='ish_turi',
        ),
        migrations.CreateModel(
            name='Bulim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolim_nomi', models.CharField(max_length=50)),
                ('bolim_id', models.PositiveIntegerField()),
                ('bolim_rahbari', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bolim', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='xodim',
            name='ish_turi',
            field=models.ManyToManyField(to='firma.ishturi_or_bolim'),
        ),
    ]
